# Generated by Django 4.2.16 on 2024-10-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_details", models.JSONField(blank=True, null=True)),
                ("state_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "records",
                "managed": True,
            },
        ),
    ]
